# Generated by Django 5.1.5 on 2025-01-19 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('contract_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('issue_date', models.DateField()),
                ('birth_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=11)),
                ('document_number', models.CharField(max_length=11)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('contract_rate', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcel_number', models.PositiveIntegerField()),
                ('parcel_amount', models.DecimalField(decimal_places=2, max_digits=11)),
                ('due_date', models.DateField()),
                ('contract_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcels', to='contracts.contract')),
            ],
            options={
                'unique_together': {('contract_id', 'parcel_number')},
            },
        ),
    ]
